### ISSUE TITLE
toBlob is not a function

### ISSUE THREAD

**Issue by tanmuhittin** [nodeca/image-blob-reduce#2]
I tried to use pica but Exif was a big pain. Thank you for this package :)

When I try to use it using the code below
```
            let fr = new FileReader();
            const reduce = require('image-blob-reduce')();
            reduce.toBlob(fr.readAsBinaryString(file), {
                max: 300,
                unsharpAmount: 90,
                unsharpRadius: 0.6,
                unsharpThreshold: 2 })
                .then(blob => {
                    addThumbnail(blob)
                });
```

I got error 
`Uncaught (in promise) TypeError: reduce.toBlob is not a function`

I could not get it worked. Is it me or something is wrong?

**Comment by puzrin** [comment]
Did you browserified it (or use /dist instead)? Try [demo src](https://github.com/nodeca/image-blob-reduce/tree/master/support/demo_template) and `npm run demo` as playground. Also first param of `toBlob()` should be Blob or File, you should not try to `.read*` it into something else. Just pass form field value as is. See how demo arrange this.

Pica options (unsharp* and others) are no supported now https://github.com/nodeca/image-blob-reduce/blob/master/index.js#L120. We just started to search optimal api, because it's a bit different for blobs. Now users are expected to override default methods or inject aditional actions. But you are right, probably we need something more simple for unsharp.

**Comment by puzrin** [comment]
Created https://github.com/nodeca/image-blob-reduce/issues/3

**Comment by puzrin** [comment]
Added pica options support and updated demo appropriately.

Is issue solved?

**Comment by tanmuhittin** [comment]
It is solved. I am using `to_blob()` function. Now it works with the config  🎉

**Comment by cruzdanilo** [comment]
why is the name different from the documentation (`to_blob` vs `toBlob`)?

**Comment by puzrin** [comment]
Ups... you are right... Need to remember where to fix.

**Comment by puzrin** [comment]
Please upgrade to 1.0.4 and use `.toBlob()` & `.toCanvas()`, as described in doc. Old names are temporary left as aliases and will be removed.
