### ISSUE TITLE
Set output quality and type

### ISSUE THREAD

**Issue by AnthonyEdmonds** [nodeca/image-blob-reduce#7]
Hi,

I may have overlooked something, however there does not seem to be any way to pass any parameters to the underlying PICA type and quality setting when using toBlob:

```
pica.resize(from, to)
  .then(result => pica.toBlob(result, 'image/jpeg', 0.90))
```

If there is a way to do this, I would appreciate some pointers and perhaps an example in the readme.

If not, I would suggest the following syntax:

```
reduce().toBlob(event.target.files[0], {
    max: 1280,
    ...
    quality: 0.8,
    type: 'image/jpeg'
})
```

Thanks,
Anthony Edmonds

**Comment by puzrin** [comment]
I'd prefer add new options only if alternatives are impossible or very complicated. You could override `_create_blob()` method of instance. That's very simple, and expected way of use.

**Comment by puzrin** [comment]
https://github.com/nodeca/image-blob-reduce/commit/55d082b51926301346d2accd18216f3b66d363f2

If you have ideas how to improve examples - PR welcome.

**Comment by cseelus** [comment]
Myself coming from **pica**, I find that Anthonys proposal would be helpful when one has to set image type and quality dynamically. Also it would make `image-blob-reduce` options more consistent with `pica .resize() options` and be overall less convoluted than having to create/override own `_create_blob()` method for these basic options.

Another problem with the `reducer._create_blob` example from here and the readme is, it would need a canvas as input (instead of image file from upload), so no drop in replacement for `.toBlob`

```javascript
const reduce = require('image-blob-reduce')();

//...

reduce
  .toBlob(image_blob, { 
    max: userImageConfig.maxSize,
    unsharpAmount: 80,
    unsharpRadius: 0.6,
    unsharpThreshold: 2,
    type: file.type,
    quality: userImageConfig.quality
})
  .then(blob => { ... });
```

In any case, excellent little image helper library you got there.
